package pl.nagrzyby.app.domain

data class MushroomSpecies(
    val id: String,
    val name: String,
    val latinName: String,
    val preferredTreeCodes: List<String>,
    val tempMin: Double,
    val tempMax: Double,
    val seasonStartMonth: Int,
    val seasonEndMonth: Int,
    val moisturePreference: String,
    val edibility: String,
    val description: String = "",
)

fun MushroomSpecies.edibilityDisplay(): String = when (edibility) {
    "choice" -> "jadalny, doskonały"
    "edible" -> "jadalny"
    "conditionally_edible" -> "jadalny po obróbce"
    "inedible" -> "niejadalny"
    "poisonous" -> "trujący"
    else -> edibility
}

object MushroomDatabase {

    val allSpecies: List<MushroomSpecies> = listOf(
        MushroomSpecies(
            id = "borowik_szlachetny",
            name = "Borowik szlachetny",
            latinName = "Boletus edulis",
            preferredTreeCodes = listOf("SO", "DB", "BK", "ŚW"),
            tempMin = 10.0, tempMax = 22.0,
            seasonStartMonth = 6, seasonEndMonth = 10,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Najbardziej poszukiwany grzyb jadalny w Polsce. Rośnie w lasach iglastych i liściastych, pod sosnami, świerkami, dębami i bukami. Ceniony za aromatyczny smak i wszechstronne zastosowanie w kuchni.",
        ),
        MushroomSpecies(
            id = "podgrzybek_brunatny",
            name = "Podgrzybek brunatny",
            latinName = "Imleria badia",
            preferredTreeCodes = listOf("SO", "ŚW"),
            tempMin = 8.0, tempMax = 22.0,
            seasonStartMonth = 6, seasonEndMonth = 11,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Jeden z najczęściej zbieranych grzybów w Polsce. Preferuje kwaśne gleby pod sosnami i świerkami. Kapelusz ciemnobrązowy, po przekrojeniu miąższ sinieje. Smaczny i aromatyczny.",
        ),
        MushroomSpecies(
            id = "kozlarz_czerwony",
            name = "Koźlarz czerwony",
            latinName = "Leccinum aurantiacum",
            preferredTreeCodes = listOf("OS", "TP"),
            tempMin = 10.0, tempMax = 22.0,
            seasonStartMonth = 7, seasonEndMonth = 10,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Charakterystyczny grzyb z pomarańczowo-czerwonym kapeluszem. Rośnie głównie pod osikami i topolami. Miąższ po przekrojeniu ciemnieje. Dobry do sosów i duszenia.",
        ),
        MushroomSpecies(
            id = "kozlarz_babka",
            name = "Koźlarz babka",
            latinName = "Leccinum scabrum",
            preferredTreeCodes = listOf("BRZ"),
            tempMin = 10.0, tempMax = 22.0,
            seasonStartMonth = 6, seasonEndMonth = 10,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Rośnie wyłącznie pod brzozami, często na obrzeżach lasów i przy drogach. Kapelusz szarobrązowy, trzon pokryty ciemnymi łuseczkami. Młode okazy najlepsze do suszenia.",
        ),
        MushroomSpecies(
            id = "maslak_zwyczajny",
            name = "Maślak zwyczajny",
            latinName = "Suillus luteus",
            preferredTreeCodes = listOf("SO"),
            tempMin = 8.0, tempMax = 22.0,
            seasonStartMonth = 5, seasonEndMonth = 11,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Grzyb tworzący symbiozę z sosną. Kapelusz śluzowaty, brązowy, łatwy do rozpoznania. Należy obierać ze skórki przed obróbką. Świetny do marynowania i zup.",
        ),
        MushroomSpecies(
            id = "kurka",
            name = "Pieprznik jadalny (kurka)",
            latinName = "Cantharellus cibarius",
            preferredTreeCodes = listOf("SO", "ŚW", "DB", "BK"),
            tempMin = 10.0, tempMax = 22.0,
            seasonStartMonth = 6, seasonEndMonth = 10,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Kurka o charakterystycznym jajecznym kolorze i lejkowatym kapeluszu. Trudno pomylić ją z innymi grzybami. Ceniona za delikatny smak i aromat. Nie robaczywieje. Idealna do sosów i jajecznicy.",
        ),
        MushroomSpecies(
            id = "rydz",
            name = "Mleczaj rydz",
            latinName = "Lactarius deliciosus",
            preferredTreeCodes = listOf("SO", "ŚW"),
            tempMin = 6.0, tempMax = 18.0,
            seasonStartMonth = 8, seasonEndMonth = 10,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Król jesiennych lasów sosnowych. Kapelusz pomarańczowy z zielonymi przebarwieniami. Po uszkodzeniu wydziela pomarańczowe mleczko. Najlepszy smażony na maśle lub w śmietanie.",
        ),
        MushroomSpecies(
            id = "kania",
            name = "Czubajka kania",
            latinName = "Macrolepiota procera",
            preferredTreeCodes = listOf("SO", "DB", "BK", "BRZ"),
            tempMin = 12.0, tempMax = 28.0,
            seasonStartMonth = 7, seasonEndMonth = 10,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Imponujący, wysoki grzyb o charakterystycznym nakrapianym kapeluszu. Rośnie na obrzeżach lasów, łąkach i pastwiskach. Młode kapelusze doskonałe jako kotlety panierowane.",
        ),
        MushroomSpecies(
            id = "opienka_miodowa",
            name = "Opieńka miodowa",
            latinName = "Armillaria mellea",
            preferredTreeCodes = listOf("SO", "ŚW", "DB", "BK", "BRZ", "GB"),
            tempMin = 5.0, tempMax = 18.0,
            seasonStartMonth = 9, seasonEndMonth = 11,
            moisturePreference = "high",
            edibility = "conditionally_edible",
            description = "Rośnie w gęstych kępach na pniakach i korzeniach drzew. Wymaga długiego gotowania przed spożyciem. Miodowy kapelusz i biały pierścień na trzonie. Późny sezon — pojawia się po deszczach.",
        ),
        MushroomSpecies(
            id = "gaska_zielonka",
            name = "Gąska zielonka",
            latinName = "Tricholoma equestre",
            preferredTreeCodes = listOf("SO"),
            tempMin = 2.0, tempMax = 12.0,
            seasonStartMonth = 9, seasonEndMonth = 11,
            moisturePreference = "medium",
            edibility = "conditionally_edible",
            description = "Grzyb o żółtozielonkawym kapeluszu rosnący w piaskach, pod sosnami. Należy spożywać z umiarem. Wyrazisty smak i zapach. Sezon późnojesienny. Wymaga ostrożności przy spożyciu.",
        ),
        MushroomSpecies(
            id = "gaska_nieksztaltna",
            name = "Gąska niekształtna",
            latinName = "Tricholoma portentosum",
            preferredTreeCodes = listOf("SO"),
            tempMin = 2.0, tempMax = 12.0,
            seasonStartMonth = 9, seasonEndMonth = 11,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Szarawy grzyb o promieniście włóknistym kapeluszu. Rośnie w lasach sosnowych i mieszanych. Pojawia się późną jesienią. Ceniony za smak, szczególnie w zupach i sosach.",
        ),
        MushroomSpecies(
            id = "borowik_ceglastopory",
            name = "Borowik ceglastopory",
            latinName = "Neoboletus luridiformis",
            preferredTreeCodes = listOf("DB", "BK", "GB"),
            tempMin = 12.0, tempMax = 22.0,
            seasonStartMonth = 7, seasonEndMonth = 10,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Grzyb o ciemnym kapeluszu i charakterystycznych czerwonych porach. Po przekrojeniu miąższ intensywnie sinieje. Wymaga długiej obróbki termicznej. Rośnie pod dębami, bukami i grabami.",
        ),
        MushroomSpecies(
            id = "podgrzybek_zajaczek",
            name = "Podgrzybek zajączek",
            latinName = "Xerocomus subtomentosus",
            preferredTreeCodes = listOf("SO", "DB", "BK"),
            tempMin = 10.0, tempMax = 22.0,
            seasonStartMonth = 6, seasonEndMonth = 10,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Delikatniejszy kuzyn podgrzybka brunatnego. Kapelusz aksamitny, oliwkowobrązowy. Preferuje lasy liściaste i mieszane. Smaczny, ale mniej aromatyczny niż podgrzybek brunatny.",
        ),
        MushroomSpecies(
            id = "kolpaczek_pierscieniowy",
            name = "Kołpaczek pierścieniowy",
            latinName = "Rozites caperatus",
            preferredTreeCodes = listOf("SO", "ŚW"),
            tempMin = 8.0, tempMax = 18.0,
            seasonStartMonth = 8, seasonEndMonth = 10,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Grzyb o żółtawym kapeluszu i charakterystycznym pierścieniu. Rośnie w wilgotnych lasach iglastych i mieszanych. Ceniony w kuchni, nadaje się do suszenia i mrożenia.",
        ),
        MushroomSpecies(
            id = "borowik_usiatkowany",
            name = "Borowik usiatkowany",
            latinName = "Boletus reticulatus",
            preferredTreeCodes = listOf("DB", "BK", "GB"),
            tempMin = 12.0, tempMax = 25.0,
            seasonStartMonth = 6, seasonEndMonth = 9,
            moisturePreference = "medium",
            edibility = "choice",
            description = "Wczesna odmiana borowika szlachetnego. Kapelusz jaśniejszy, trzon pokryty delikatną siateczką. Rośnie głównie pod dębami i bukami. Pojawia się już w czerwcu. Aromatyczny i smaczny.",
        ),
    )
}
